application: xiidec
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /humans\.txt
  static_files: static/humans.txt
  upload: static/humans\.txt

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /colamone/(.*\.(html|js|css|png|gif))
  static_files: static/colamone/\1
  upload: static/colamone/(.*\.(html|js|css|png|gif))


- url: /colamone_vs/(.*\.(html|js|css))
  static_files: static/colamone_vs/\1
  upload: static/colamone_vs/(.*\.(html|js|css))

- url: /colamone_beta/(.*\.(html|js|css|png|gif))
  static_files: static/colamone_beta/\1
  upload: static/colamone_beta/(.*\.(html|js|css|png|gif))

- url: /myboardgame/boardgame.html
  static_files: static/colamone/colamone.html
  upload: static/colamone/(.*\.(html|js|css))

- url: /myboardgame/(.*\.(html|js|css|gif))
  static_files: static/colamone/\1
  upload: static/colamone/(.*\.(html|js|css|gif))

- url: /google9bb6b05fe7c75d83.html
  static_files: static/google9bb6b05fe7c75d83.html
  upload: static/google9bb6b05fe7c75d83.html

- url: /markov2.html
  static_files: static/markov2.html
  upload: static/markov2.html

- url: /(.*\.(gif|png|jpg|js|css|wav|zip))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|js|css|wav|zip))

- url: /sample/(.*\.(html))
  static_files: static/sample/\1
  upload: static/sample/(.*\.(html))

- url: /jasmine/(.*)
  static_files: static/jasmine/\1
  upload: static/jasmine/(.*)

- url: /test\.html
  script: test.app

- url: /hello\.html
  script: hello.app

- url: /markov\.html
  script: markov.app
 
- url: /vschart\.html
  script: vschart.app
  
- url: /abface\.html
  script: abface.app
  
- url: .*
  script: main.app
libraries:
- name: webapp2
  version: "2.5.2"
  
inbound_services:
- warmup